OUTDIR = build
OBJDIR = $(OUTDIR)\obj
INCLUDES = /Iinclude

CC = cl
LD = link
COMMON_CFLAGS = /nologo /W4 /O2 /TC $(INCLUDES)

all: dirs $(OUTDIR)\pbfgen.exe $(OUTDIR)\pbf-runner.exe $(OUTDIR)\simple-memory-loader.exe $(OUTDIR)\thread-memory-loader.exe $(OUTDIR)\injection-target.exe $(OUTDIR)\peprobe.exe $(OUTDIR)\native-maptest.exe $(OUTDIR)\native-bin-gen.exe $(OUTDIR)\native-bin-runner.exe $(OUTDIR)\clr-maptest.exe $(OUTDIR)\managed-bin-pack.exe $(OUTDIR)\managed-bin-runner.exe $(OUTDIR)\pbf.exe $(OUTDIR)\native-demo.dll $(OUTDIR)\native-demo.bin $(OUTDIR)\native-exe-demo.exe $(OUTDIR)\native-exe-demo.bin $(OUTDIR)\example\TEST.EXE $(OUTDIR)\example\TEST.bin $(OUTDIR)\demo.bin $(OUTDIR)\standalone-demo.bin $(OBJDIR)\reloc_bad.obj

dirs:
	@if not exist "$(OUTDIR)" mkdir "$(OUTDIR)"
	@if not exist "$(OBJDIR)" mkdir "$(OBJDIR)"
	@if not exist "$(OUTDIR)\example" mkdir "$(OUTDIR)\example"

$(OBJDIR)\pbfgen.obj: tools\pbfgen.c
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ tools\pbfgen.c

$(OUTDIR)\pbfgen.exe: $(OBJDIR)\pbfgen.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\pbfgen.obj advapi32.lib

$(OBJDIR)\runner.obj: runner\runner.c include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ runner\runner.c

$(OUTDIR)\pbf-runner.exe: $(OBJDIR)\runner.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\runner.obj advapi32.lib

$(OBJDIR)\simple_memory_loader.obj: runner\simple_memory_loader.c
	$(CC) $(COMMON_CFLAGS) /MT /c /Fo:$@ runner\simple_memory_loader.c

$(OUTDIR)\simple-memory-loader.exe: $(OBJDIR)\simple_memory_loader.obj
	$(LD) /nologo /MACHINE:X64 /SUBSYSTEM:CONSOLE /OUT:$@ $(OBJDIR)\simple_memory_loader.obj

$(OBJDIR)\thread_memory_loader.obj: runner\thread_memory_loader.c include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /MT /c /Fo:$@ runner\thread_memory_loader.c

$(OUTDIR)\thread-memory-loader.exe: $(OBJDIR)\thread_memory_loader.obj
	$(LD) /nologo /MACHINE:X64 /SUBSYSTEM:CONSOLE /OUT:$@ $(OBJDIR)\thread_memory_loader.obj

$(OBJDIR)\injection_target.obj: payloads\injection_target.c
	$(CC) $(COMMON_CFLAGS) /MT /c /Fo:$@ payloads\injection_target.c

$(OUTDIR)\injection-target.exe: $(OBJDIR)\injection_target.obj
	$(LD) /nologo /MACHINE:X64 /SUBSYSTEM:CONSOLE /OUT:$@ $(OBJDIR)\injection_target.obj

$(OBJDIR)\peprobe.obj: tools\peprobe.c
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ tools\peprobe.c

$(OUTDIR)\peprobe.exe: $(OBJDIR)\peprobe.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\peprobe.obj

$(OBJDIR)\native_maptest.obj: native\native_maptest.c include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ native\native_maptest.c

$(OUTDIR)\native-maptest.exe: $(OBJDIR)\native_maptest.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\native_maptest.obj

$(OBJDIR)\native_demo.obj: payloads\native_demo.c include\pbf_abi.h
	$(CC) /nologo /W4 /O2 /TC /GS- /Zl $(INCLUDES) /c /Fo:$@ payloads\native_demo.c

$(OBJDIR)\native_dependency.obj: payloads\native_dependency.c
	$(CC) /nologo /W4 /O2 /TC /GS- /Zl $(INCLUDES) /c /Fo:$@ payloads\native_dependency.c

$(OBJDIR)\native_dependency_leaf.obj: payloads\native_dependency_leaf.c
	$(CC) /nologo /W4 /O2 /TC /GS- /Zl $(INCLUDES) /c /Fo:$@ payloads\native_dependency_leaf.c

$(OUTDIR)\pbfleaf.dll: $(OBJDIR)\native_dependency_leaf.obj
	$(LD) /nologo /DLL /MACHINE:X64 /DYNAMICBASE /NXCOMPAT /ENTRY:DllMain /OUT:$(OUTDIR)\pbfleaf.dll /IMPLIB:$(OUTDIR)\pbfleaf.lib $(OBJDIR)\native_dependency_leaf.obj

$(OUTDIR)\pbfleaf.lib: $(OUTDIR)\pbfleaf.dll

$(OUTDIR)\pbfdep.dll: $(OBJDIR)\native_dependency.obj $(OUTDIR)\pbfleaf.lib
	$(LD) /nologo /DLL /MACHINE:X64 /DYNAMICBASE /NXCOMPAT /ENTRY:DllMain /OUT:$(OUTDIR)\pbfdep.dll /IMPLIB:$(OUTDIR)\pbfdep.lib $(OBJDIR)\native_dependency.obj $(OUTDIR)\pbfleaf.lib

$(OUTDIR)\pbfdep.lib: $(OUTDIR)\pbfdep.dll

$(OUTDIR)\native-demo.dll: $(OBJDIR)\native_demo.obj $(OUTDIR)\pbfdep.lib
	$(LD) /nologo /DLL /MACHINE:X64 /DYNAMICBASE /NXCOMPAT /ENTRY:DllMain /OUT:$@ $(OBJDIR)\native_demo.obj $(OUTDIR)\pbfdep.lib kernel32.lib

$(OBJDIR)\native_exe_demo.obj: payloads\native_exe_demo.c
	$(CC) $(COMMON_CFLAGS) /MT /c /Fo:$@ payloads\native_exe_demo.c

$(OUTDIR)\native-exe-demo.exe: $(OBJDIR)\native_exe_demo.obj $(OUTDIR)\pbfdep.lib
	$(LD) /nologo /MACHINE:X64 /DYNAMICBASE /NXCOMPAT /SUBSYSTEM:CONSOLE /OUT:$@ $(OBJDIR)\native_exe_demo.obj $(OUTDIR)\pbfdep.lib

$(OBJDIR)\native_stub.obj: native\pic_stub.c include\pbf_native.h include\pbf_abi.h
	$(CC) /nologo /W4 /O2 /TC /GS- /GR- /Zl /Oi- /Gy- $(INCLUDES) /c /Fo:$@ native\pic_stub.c

$(OBJDIR)\native_bin_gen.obj: tools\native_bin_gen.c include\pbf_native.h include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ tools\native_bin_gen.c

$(OUTDIR)\native-bin-gen.exe: $(OBJDIR)\native_bin_gen.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\native_bin_gen.obj advapi32.lib

$(OBJDIR)\native_bin_runner.obj: runner\native_bin_runner.c include\pbf_native.h include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ runner\native_bin_runner.c

$(OUTDIR)\native-bin-runner.exe: $(OBJDIR)\native_bin_runner.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\native_bin_runner.obj advapi32.lib

$(OBJDIR)\clr_maptest.obj: managed\clr_maptest.c
	$(CC) $(COMMON_CFLAGS) /wd4201 /c /Fo:$@ managed\clr_maptest.c

$(OUTDIR)\clr-maptest.exe: $(OBJDIR)\clr_maptest.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\clr_maptest.obj mscoree.lib ole32.lib oleaut32.lib

$(OBJDIR)\clr_host_lib.obj: managed\clr_maptest.c include\pbf_clr_host.h
	$(CC) $(COMMON_CFLAGS) /wd4201 /DPBF_CLR_LIBRARY /c /Fo:$@ managed\clr_maptest.c

$(OBJDIR)\managed_pic_stub.obj: managed\pic_stub.c include\pbf_managed.h include\pbf_abi.h
	$(CC) /nologo /W4 /O2 /TC /GS- /GR- /Zl /Oi- /Gy- $(INCLUDES) /c /Fo:$@ managed\pic_stub.c

$(OBJDIR)\managed_bin_pack.obj: tools\managed_bin_pack.c include\pbf_managed.h include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ tools\managed_bin_pack.c

$(OUTDIR)\managed-bin-pack.exe: $(OBJDIR)\managed_bin_pack.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\managed_bin_pack.obj advapi32.lib

$(OBJDIR)\managed_bin_runner.obj: runner\managed_bin_runner.c include\pbf_managed.h include\pbf_clr_host.h include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ runner\managed_bin_runner.c

$(OUTDIR)\managed-bin-runner.exe: $(OBJDIR)\managed_bin_runner.obj $(OBJDIR)\clr_host_lib.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\managed_bin_runner.obj $(OBJDIR)\clr_host_lib.obj mscoree.lib ole32.lib oleaut32.lib advapi32.lib

$(OBJDIR)\pbf_cli.obj: tools\pbf_cli.c include\pbf_native.h include\pbf_managed.h include\pbf_abi.h
	$(CC) $(COMMON_CFLAGS) /c /Fo:$@ tools\pbf_cli.c

$(OUTDIR)\pbf.exe: $(OBJDIR)\pbf_cli.obj
	$(LD) /nologo /OUT:$@ $(OBJDIR)\pbf_cli.obj bcrypt.lib

$(OUTDIR)\native-demo.bin: $(OBJDIR)\native_stub.obj $(OUTDIR)\native-demo.dll $(OUTDIR)\native-bin-gen.exe
	$(OUTDIR)\native-bin-gen.exe $(OBJDIR)\native_stub.obj $(OUTDIR)\native-demo.dll $@ --force

$(OUTDIR)\native-exe-demo.bin: $(OBJDIR)\native_stub.obj $(OUTDIR)\native-exe-demo.exe $(OUTDIR)\native-bin-gen.exe
	$(OUTDIR)\native-bin-gen.exe $(OBJDIR)\native_stub.obj $(OUTDIR)\native-exe-demo.exe $@ --force

$(OBJDIR)\test1.obj: payloads\test1.c
	$(CC) /nologo /W4 /O2 /TC /GS- /Zl $(INCLUDES) /c /Fo:$@ payloads\test1.c

$(OUTDIR)\example\test1.dll: $(OBJDIR)\test1.obj
	$(LD) /nologo /DLL /MACHINE:X64 /DYNAMICBASE /NXCOMPAT /ENTRY:DllMain /OUT:$@ /IMPLIB:$(OUTDIR)\example\test1.lib $(OBJDIR)\test1.obj

$(OUTDIR)\example\test1.lib: $(OUTDIR)\example\test1.dll

$(OBJDIR)\test_exe.obj: payloads\test_exe.c
	$(CC) $(COMMON_CFLAGS) /MT /c /Fo:$@ payloads\test_exe.c

$(OUTDIR)\example\TEST.EXE: $(OBJDIR)\test_exe.obj $(OUTDIR)\example\test1.lib
	$(LD) /nologo /MACHINE:X64 /DYNAMICBASE /NXCOMPAT /SUBSYSTEM:CONSOLE /OUT:$@ $(OBJDIR)\test_exe.obj $(OUTDIR)\example\test1.lib

$(OUTDIR)\example\TEST.bin: $(OBJDIR)\native_stub.obj $(OUTDIR)\example\TEST.EXE $(OUTDIR)\native-bin-gen.exe
	$(OUTDIR)\native-bin-gen.exe $(OBJDIR)\native_stub.obj $(OUTDIR)\example\TEST.EXE $@ --force

$(OBJDIR)\demo.obj: payloads\demo.c include\pbf_abi.h
	$(CC) /nologo /W4 /O2 /TC /GS- /GR- /Zl $(INCLUDES) /c /Fo:$@ payloads\demo.c

$(OBJDIR)\reloc_bad.obj: payloads\reloc_bad.c
	$(CC) /nologo /W4 /O2 /TC /GS- /GR- /Zl $(INCLUDES) /c /Fo:$@ payloads\reloc_bad.c

$(OUTDIR)\demo.bin: $(OBJDIR)\demo.obj $(OUTDIR)\pbfgen.exe
	$(OUTDIR)\pbfgen.exe $(OBJDIR)\demo.obj $@ --force

$(OBJDIR)\standalone_demo.obj: payloads\standalone_demo.c
	$(CC) /nologo /W4 /O2 /TC /GS- /GR- /Zl $(INCLUDES) /c /Fo:$@ payloads\standalone_demo.c

$(OUTDIR)\standalone-demo.bin: $(OBJDIR)\standalone_demo.obj $(OUTDIR)\pbfgen.exe
	$(OUTDIR)\pbfgen.exe $(OBJDIR)\standalone_demo.obj $@ --force

clean:
	@if exist "$(OUTDIR)" rmdir /S /Q "$(OUTDIR)"
